alias: "BYD Akkusteuerung Control"
description: "Controls BYD Akku operations with status logs"
trigger:
  - platform: state
    entity_id: input_select.byd_akkusteuerung
variables:
  charging_power: >
    {% set power = states('input_number.akkusteuerung_ladestaerke_soll') | default('0') %}
    {% set clean_value = power | string | replace(' ', '') | replace('\n', '') | replace('\r', '') | replace('\t', '') %}
    {{ clean_value | int if clean_value != 'unknown' and clean_value != '' and clean_value is not none else 0 }}
  discharge_power: >
    {% set power = states('input_number.akkusteuerung_entladestaerke_soll') | default('0') %}
    {% set clean_value = power | string | replace(' ', '') | replace('\n', '') | replace('\r', '') | replace('\t', '') %}
    {{ clean_value | int if clean_value != 'unknown' and clean_value != '' and clean_value is not none else 0 }}
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.byd_akkusteuerung
            state: BYD Akku schnell Laden
        sequence:
          - service: logbook.log
            data:
              name: "BYD Akkusteuerung Control"
              message: >-
                Status changed to 'BYD Akku schnell Laden'. Setting Modbus
                register 40151 to 802 (indicates high-speed loading mode) and
                adjusting load with register 40149.
          - service: modbus.write_register
            data:
              hub: sma_solar
              address: 40151
              slave: 3
              value:
                - 0
                - 802
          - delay: "00:00:05"
          - service: modbus.write_register
            data:
              hub: sma_solar
              address: 40149
              slave: 3
              value:
                - 65535
                - "{{ 65535 - charging_power }}"
      - conditions:
          - condition: state
            entity_id: input_select.byd_akkusteuerung
            state: BYD Akku schnell Entladen
        sequence:
          - service: logbook.log
            data:
              name: "BYD Akkusteuerung Control"
              message: >-
                Status changed to 'BYD Akku schnell Entladen'. Setting Modbus
                register 40151 to 802 (indicates high-speed discharging mode)
                and adjusting discharge with register 40149.
          - service: modbus.write_register
            data:
              hub: sma_solar
              address: 40151
              slave: 3
              value:
                - 0
                - 802
          - delay: "00:00:05"
          - service: modbus.write_register
            data:
              hub: sma_solar
              address: 40149
              slave: 3
              value:
                - 0
                - "{{ discharge_power }}"
      - conditions:
          - condition: state
            entity_id: input_select.byd_akkusteuerung
            state: BYD Akku Pausieren
        sequence:
          - service: logbook.log
            data:
              name: "BYD Akkusteuerung Control"
              message: >-
                Status changed to 'BYD Akku Pausieren'. Setting Modbus register
                40151 to 802 (indicates pause mode) and halting load/discharge
                with register 40149 set to 0.
          - service: modbus.write_register
            data:
              hub: sma_solar
              address: 40151
              slave: 3
              value:
                - 0
                - 802
          - delay: "00:00:05"
          - service: modbus.write_register
            data:
              hub: sma_solar
              address: 40149
              slave: 3
              value:
                - 0
                - 0
      - conditions:
          - condition: state
            entity_id: input_select.byd_akkusteuerung
            state: BYD Akku Normalbetrieb
        sequence:
          - service: logbook.log
            data:
              name: "BYD Akkusteuerung Control"
              message: >-
                Status changed to 'BYD Akku Normalbetrieb'. Setting Modbus
                register 40151 to 803 (indicates normal operating mode).
          - service: modbus.write_register
            data:
              hub: sma_solar
              address: 40151
              slave: 3
              value:
                - 0
                - 803
mode: single